include:
  - board: nice_nano_v2
    shield: jaan_left nice_view_adapter nice_view_gem
  - board: nice_nano_v2
    shield: jaan_right nice_view_adapter nice_view_gem
  # - board: seeeduino_xiao_ble
  #   shield: settings_reset
# there is no settingsreset (needed) for the XIAO
