include:
  - board: nice_nano_v2
    shield: jaan_left
  - board: nice_nano_v2
    shield: jaan_right
  # - board: seeeduino_xiao_ble
  #   shield: settings_reset
# there is no settingsreset (needed) for the XIAO
