include:
  - board: nice_nano_v2
    shield: jaan_left nice_view_adapter nice_view_gem
    # snippet: studio-rpc-usb-uart
    # cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: jaan_right nice_view_adapter nice_view_gem
  - board: nice_nano_v2
    shield: settings_reset
# there is no settingsreset (needed) for the XIAO
