# syntax=docker/dockerfile:1.4
# vim: filetype=dockerfile
FROM private/nix-zmk-base
RUN source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh && nix profile install nixpkgs#direnv nixpkgs#nix-direnv && \
    echo 'eval "$(direnv hook bash)"' >> ~/.bashrc && \
    mkdir -p ~/.config/direnv && echo 'source ~/.nix-profile/share/nix-direnv/direnvrc' >> ~/.config/direnv/direnvrc && \
    source ~/.bashrc

RUN mkdir -p ~/.config/direnv && \
    echo '[whitelist]' > ~/.config/direnv/direnv.toml && \
    echo 'prefix = [ "/root/zmk-workspace" ]' >> ~/.config/direnv/direnv.toml

RUN --mount=type=bind,source=$PWD,target=/root/zmk-workspace,rw \
    /tmp/init_direnv.sh


WORKDIR /root
CMD ["/bin/bash"]

