# syntax=docker/dockerfile:1.4
# vim: filetype=dockerfile
# use:
#    dk buildx build -t private/nix-zmk --progress=plain -f Dockerfile-nix .

FROM private/nix-zmk-base

COPY ./scripts/docker/.bashrc /root

RUN source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh && nix profile install nixpkgs#direnv nixpkgs#nix-direnv && \
    echo 'eval "$(direnv hook bash)"' >> ~/.bashrc && \
    mkdir -p ~/.config/direnv && echo 'source ~/.nix-profile/share/nix-direnv/direnvrc' >> ~/.config/direnv/direnvrc && \
    source ~/.bashrc

RUN mkdir -p ~/.config/direnv && \
    echo '[whitelist]' > ~/.config/direnv/direnv.toml && \
    echo 'prefix = [ "/root/zmk-workspace" ]' >> ~/.config/direnv/direnv.toml

RUN --mount=type=bind,source=$PWD,target=/root/zmk-workspace,rw \
    /root/zmk-workspace/scripts/docker/init_direnv.sh

# COPY ./scripts/docker/nvimrc-vscode /root/.nvimrc-vscode
RUN mkdir -p ~/.config/nvim/{autoload,undo,backup} && \
    cd ~/.config/nvim && \
    ln -s ~/zmk-workspace/scripts/docker/nvimrc-vscode init.vim

WORKDIR /root
CMD ["/bin/bash"]
