# version: "3.9"
services:
  build:
    # user: ${USER_ID}:${GROUP_ID}
    image: private/nix-zmk
    environment:
      # - ZEPHYR_VERSION=${ZEPHYR_VERSION}
      # - zephyr_version=${ZEPHYR_VERSION}
      - USERNAME=${USERNAME}
    secrets:
      - khersak_ssh_key
        # target: /home/hamid/.ssh/id_ed25519
        # uid: ${USER_ID}
        # gid: ${GROUP_ID}
        # mode: 400
    working_dir: /root/zmk-workspace
    # env_file: env.list
    command:
      - bash
      - -c
      - |
        git
    volumes:
      - /tmp:/tmp
      - /Volumes/manzel/hamid/projects/hobbies/zmk_firmwares/zmk-config-jaan:/root/zmk-workspace:rw
      # - zmk_config_root:/root/zmk-workspace
secrets:
  khersak_ssh_key:
    file: ${HOST_CONFIG_DIR}/.khersak_id_rsa
# volumes:
#   zmk_config_root:
#     name: zmk-config-jaan
#     external: true
