file_format: "1"
id: jaan
name: Jaan
type: shield
url: https://github.com/spamwax/jaan
requires: [nice_nano_v2]
# exposes: [i2c_oled] # this is from juriform36
features:
  - keys
  # - display
siblings:
  - jaan_left
  - jaan_right
