manifest:
  remotes:
    - name: spamwax-zmk
      url-base: https://github.com/spamwax
  projects:
    - name: zmk
      remote: spamwax-zmk
      revision: main
      import: app/west.yml
  self:
    path: config