manifest:
  remotes:
    - name: spamwax-zmk
      url-base: https://github.com/spamwax
    - name: dhruvinsh
      url-base: https://github.com/dhruvinsh
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: spamwax-zmk
      revision: mainline
      clone-depth: 1
      import: app/west.yml
    - name: zmk-tri-state
      remote: dhruvinsh
      revision: main
    - name: zmk-num-word
      remote: dhruvinsh
      revision: main
    - name: zmk-auto-layer
      remote: urob
      revision: v0.1 # set to same version as zmk
  self:
    path: config
